name: Gooman
markdown: kramdown
highlighter: rouge

url: http://gooman-rus.github.io
#enforce_ssl: yougo.website

paginate: 5
paginate_path: "/page:num/"

plugins:
  - jekyll-sitemap
  - jekyll-paginate
