name: Gooman
markdown: kramdown
highlighter: rouge

url: https://gooman-rus.github.io/
enforce_ssl: gooman-rus.github.io

paginate: 5
paginate_path: "/page:num/"

plugins:
  - jekyll-sitemap
  - jekyll-paginate
